# Generated by Django 4.0.4 on 2022-06-17 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='children',
            old_name='child_id',
            new_name='childId',
        ),
        migrations.RenameField(
            model_name='children',
            old_name='parent_id',
            new_name='parentId',
        ),
    ]
