# Generated by Django 4.0.4 on 2022-06-18 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_main_uid_alter_main_id_alter_main_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='childId',
            field=models.UUIDField(),
        ),
    ]
