# Generated by Django 4.0.4 on 2022-06-18 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_children_childid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='parentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.main'),
        ),
    ]
