# Generated by Django 4.0.4 on 2022-06-18 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_children_parentid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='children',
            old_name='parentId',
            new_name='main',
        ),
    ]
