# Generated by Django 4.0.4 on 2022-06-18 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_children_childid_alter_main_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='childId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='childid', to='api.main', unique=True),
        ),
        migrations.AlterField(
            model_name='children',
            name='main',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.main'),
        ),
    ]
