# Generated by Django 4.0.4 on 2022-06-21 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_delete_children'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='type',
            field=models.CharField(choices=[('OFFER', 'OFFER'), ('CATEGORY', 'CATEGORY')], max_length=255),
        ),
    ]
