# Generated by Django 4.0.4 on 2022-06-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_main_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='type',
            field=models.CharField(max_length=255),
        ),
    ]
