# Generated by Django 4.0.4 on 2022-06-21 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_main_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='parentId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.main'),
        ),
    ]
